// <auto-generated />
using System;
using Airbb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airbb.Migrations
{
    [DbContext(typeof(AirbbContext))]
    partial class AirbbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Airbb.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "Seattle"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "Denver"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Houston"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Orlando"
                        });
                });

            modelBuilder.Entity("Airbb.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservation");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            ReservationEndDate = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 1
                        },
                        new
                        {
                            ReservationId = 2,
                            ReservationEndDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 2
                        },
                        new
                        {
                            ReservationId = 3,
                            ReservationEndDate = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReservationStartDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResidenceId = 3
                        });
                });

            modelBuilder.Entity("Airbb.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BathroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BuiltYear")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PricePerNight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidencePicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Residence");

                    b.HasData(
                        new
                        {
                            ResidenceId = 1,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            BuiltYear = new DateTime(1899, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestNumber = 2,
                            LocationId = 1,
                            Name = "Seattle Skyline Silhouette",
                            PricePerNight = "130",
                            ResidencePicture = "SeattleSkylineSilhouette.png",
                            UserId = 1
                        },
                        new
                        {
                            ResidenceId = 2,
                            BathroomNumber = 2,
                            BedroomNumber = 3,
                            BuiltYear = new DateTime(1901, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestNumber = 6,
                            LocationId = 2,
                            Name = "Denver Mountain Cabin",
                            PricePerNight = "150",
                            ResidencePicture = "DenverMountainCabin.png",
                            UserId = 4
                        },
                        new
                        {
                            ResidenceId = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 2,
                            BuiltYear = new DateTime(2001, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestNumber = 4,
                            LocationId = 3,
                            Name = "Houston Downtown Loft",
                            PricePerNight = "95",
                            ResidencePicture = "HoustonDowntownLoft.png",
                            UserId = 3
                        },
                        new
                        {
                            ResidenceId = 4,
                            BathroomNumber = 3,
                            BedroomNumber = 4,
                            BuiltYear = new DateTime(1989, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestNumber = 8,
                            LocationId = 4,
                            Name = "Orlando Family Villa",
                            PricePerNight = "170",
                            ResidencePicture = "OrlandoFamilyVilla.png",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Airbb.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DOB = new DateTime(1997, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lucas.bennett@gmail.com",
                            Name = "Lucas Bennett",
                            PhoneNo = "955-707-8080",
                            SSN = "124-866-6878",
                            UserType = "Owner"
                        },
                        new
                        {
                            UserId = 2,
                            DOB = new DateTime(2000, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "isabella.perez@gmail.com",
                            Name = "Isabella Perez",
                            PhoneNo = "201-909-1010",
                            SSN = "421-897-4356",
                            UserType = "Client"
                        },
                        new
                        {
                            UserId = 3,
                            DOB = new DateTime(1999, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ethan.clark@gmail.com",
                            Name = "Ethan Clark",
                            PhoneNo = "614-111-2121",
                            SSN = "124-409-6780",
                            UserType = "Admin"
                        },
                        new
                        {
                            UserId = 4,
                            DOB = new DateTime(1999, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jim.greevy@gmail.com",
                            Name = "Jim Greevy",
                            PhoneNo = "216-090-6767",
                            SSN = "989-456-4567",
                            UserType = "Owner"
                        });
                });

            modelBuilder.Entity("Airbb.Models.Reservation", b =>
                {
                    b.HasOne("Airbb.Models.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("Airbb.Models.Residence", b =>
                {
                    b.HasOne("Airbb.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airbb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
